### ISSUE TITLE
Add Publisher License to status page

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-status-page#5]
The required info is now stored in database, publisher.data

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Publisher License to status page](https://trello.com/c/JZMZ2PI0/64-add-publisher-license-to-status-page)

**Comment by michaelwood** [comment]
https://github.com/openactive/conformance-status-page/commit/2cc01054ffaef441504f955a7b1a9987bb53aace
